const API_CALL_REQUEST = 'API_CALL_REQUEST';
const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
const API_CALL_FAILURE = 'API_CALL_FAILURE';

export default {
  API_CALL_REQUEST,
  API_CALL_SUCCESS,
  API_CALL_FAILURE
};
