const API_TWO_CALL_REQUEST = 'API_TWO_CALL_REQUEST';
const API_TWO_CALL_SUCCESS = 'API_TWO_CALL_SUCCESS';
const API_TWO_CALL_FAILURE = 'API_TWO_CALL_FAILURE';

export default {
  API_TWO_CALL_REQUEST,
  API_TWO_CALL_SUCCESS,
  API_TWO_CALL_FAILURE
};
