const GET_DOG_REQUEST = 'GET_DOG_REQUEST';
const GET_DOG_SUCCESS = 'GET_DOG_SUCCESS';
const GET_DOG_FAILURE = 'GET_DOG_FAILURE';

export default {
  GET_DOG_REQUEST,
  GET_DOG_SUCCESS,
  GET_DOG_FAILURE
};
